name: Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  MICROPYTHON_REV: v1.29.0

jobs:
  build-zephyr-stable:
    name: Build Artifacts with stable zephyr
    runs-on: ubuntu-latest
    env:
      ZEPHYR_REV: v4.4.2
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup
        run: make app/west.yml

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: app
          toolchains: arm-zephyr-eabi

      - name: Building For BeaglePlay
        run: make dist/beagleplay-cc1352p7.bin.xz

      - name: Building For BeagleConnect Freedom
        run: make dist/beagleconnect_freedom.bin.xz

  build-zephyr-main:
    name: Build Artifacts with mainline zephyr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends mtools
          make app/west.yml

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: app
          toolchains: aarch64-zephyr-elf

      - name: Building For PocketBeagle 2
        run: make dist/pocketbeagle_2-am6254-a53.bin.xz
