name: Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  MICROPYTHON_REV: v1.29.0

jobs:
  build-zephyr-stable:
    name: Build Artifacts with stable zephyr
    runs-on: ubuntu-latest
    env:
      ZEPHYR_REV: v4.4.2
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup
        run: make app/west.yml

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: app
          toolchains: arm-zephyr-eabi

      - name: Building For BeaglePlay
        run: make dist/beagleplay-cc1352p7.bin.xz

      - name: Building For BeagleConnect Freedom
        run: make dist/beagleconnect_freedom.bin.xz

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: artifacts-zephyr-stable
          path: |
            dist/*

  build-zephyr-main:
    name: Build Artifacts with mainline zephyr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends mtools
          make app/west.yml

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: app
          toolchains: aarch64-zephyr-elf

      - name: Building For PocketBeagle 2
        run: |
          make dist/pocketbeagle_2-am6254-a53.bin.xz
          make -j$(nproc) dist/pocketbeagle_2-am6254-a53.img.xz

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: artifacts-zephyr-main
          path: |
            dist/*

  release:
    name: Upload Release artifacts
    needs:
      - build-zephyr-main
      - build-zephyr-stable
    runs-on: ubuntu-slim
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Download all artifacts
        uses: actions/download-artifact@v8
        with:
          path: dist
          merge-multiple: true
      - run: ls -laR dist

      - name: Generate os_list.json
        run: ./os_list.py continuous-release

      - name: Create Pre-Release
        uses: softprops/action-gh-release@v3
        with:
          prerelease: true
          name: Continuous Release
          tag_name: continuous-release
          files: dist/*
